### ISSUE TITLE
yo sails-rest-api not working

### ISSUE THREAD

**Issue by antoniobarbosa** [ghaiklor/generator-sails-rest-api#290] opened 2016-10-18 15:28 UTC
I am trying to run yo sails-rest-api command the it asks me the project name. and finish, don't do anything else! nothing happens on my project folder,
![image](https://cloud.githubusercontent.com/assets/5209728/19484516/a70ac804-9536-11e6-8409-e4f7c36569d7.png)

**Comment by ghaiklor** [comment] 2016-10-19 08:35
@antoniobarbosa I didn't test it on Windows, so I can't guarantee it will work. Tested under Mac OS and Linux only.

**Comment by vystydp** [comment] 2016-10-19 09:14
I have the same problem on Ubuntu

**Comment by vystydp** [comment] 2016-10-19 15:25
@ghaiklor It Works under v1.3.6!

**Comment by ghaiklor** [comment] 2016-10-19 16:20
@vystydp can you help with debugging what exactly goes wrong? The only changes between 1.3.6 and 1.3.7 is in package dependencies and one-line fix. I suppose that the issue is with some of dependencies.

**Comment by ghaiklor** [comment] 2016-10-19 16:21
@vystydp I can say even more. Try to downgrade `yeoman-generator` package by minor versions and find the version where it works. I think the issue in that.

**Comment by mikedevita** [comment] 2016-10-19 19:34
i can confirm 1.3.7 is broken on node, both 4.6.1 and 6x.. bumping down to generator-sails-rest-api@1.3.6 fixes it and lets me bo through thesteps.

**Comment by ghaiklor** [comment] 2016-10-20 09:29
@mikedevita @vystydp @antoniobarbosa updated to v1.3.8. Check it out, should work.

**Comment by antoniobarbosa** [comment] 2016-10-20 10:46
@ghaiklor it's working fine for me now!!

**Comment by ghaiklor** [comment] 2016-10-20 10:48
Great, I'm closing the issue. Thanks guys, for reporting 👍

**Closed by ghaiklor** 2016-10-20 10:48 UTC
