### ISSUE TITLE
JWT CipherService config

### ISSUE THREAD

**Issue by rkcreation** [ghaiklor/generator-sails-rest-api#133] opened 2015-10-28 14:09 UTC
Hi,

After generating a new project, I can sign up and sign in, but I'm not able to access other routes, due to an `invalid signature` jsonwebtoken error.
After investigating, for a working JWT authentication, I have simply changed the key `secretOrKey` to `secretKey` in `config/services/cipher.js`. Without this, CipherService generates the JWT with `DEFAULT_SECRET_KEY`, but passport-jwt checks are made with the secret key configured in `config/passport.js`, leading an `invalid signature` error each time.

I don't know if it's due to my project, or if it's a bug due to `sails-service-cipher`, or if it's an issue of this project, but I share my experience.

**Comment by weyert** [comment] 2015-10-28 17:43
This also happens when you create a new one through yeoman

**Comment by ghaiklor** [comment] 2015-10-28 18:13
When you are creating project through yeoman generator it works in the following way:

1) If you have answered Yes on "Authentication layer" question then it generates secret key and configure `CipherService` with its key.

2) If not, then there is not authentication layer at all and should works.

Can you, guys, gave me more information how can I reproduce it?

**Comment by weyert** [comment] 2015-10-28 20:14
I will try. I have emailed you regarding an issue with FacebookStrategy and the error Cannot read property 'onPassportAuth' of undefined

**Comment by ghaiklor** [comment] 2015-10-29 12:13
@weyert @rkcreation I can't reproduce your issue.

**Comment by rkcreation** [comment] 2015-10-29 13:54
I have set Authentication layer with the generator (Yes).
Generator version : 1.0.2
Windows Node version : 4.2.1

My `config/services/cipher.js` after generating : 
```js
export default {
  services: {
    cipher: {
      jwt: {
        secretOrKey: 'XXXXXX',
      }
    }
  }
}
```
And, for a working JWT auth, I have changed `secretOrKey` to `secretKey`

I encounter also the issue mentioned by @weyert : `Cannot read property onPassportAuth of undefined`, resolved by adding object export in `config/passport.js` : 
```js
export default {
  passport: {
    onPassportAuth: (req, res, error, user, info) => {
      if (error || !user) return res.negotiate(error || info);
      return res.ok({
        token: CipherService.jwt.encodeSync({id: user.id}),
        user: user
      });
    }
  }
};
```

**Comment by ghaiklor** [comment] 2015-10-29 14:01
@rkcreation this is related to #135 and already fixed in the latest version. You can update generator and run `yo sails-rest-api:authentication` again.

**Comment by rkcreation** [comment] 2015-10-29 17:53
@ghaiklor #135 and the last version fix the onPassportAuth definition, but not the issue that I'm talking.
I generate a fresh install with v1.0.6, and `config/services/cipher.js` set the key `secretOrKey` and the node module sails-service-cipher checks (in `lib/JwtCipher.js` lines 34 and 71) for a config key `secretKey`

In my last install, generated secret key is : `4fab47b9e6b8b91a74c74547d9f3629f0712eff83f895c37c5a70e963c945fe3`

When I authenticate, CipherService returns (without my fix) a token generated with the default key in sails-service-cipher : `DEFAULT_SECRET_KEY`

And after, when I request some API resources, passport verify my JWT with the real key : `4fab47b9e6b8b91a74c74547d9f3629f0712eff83f895c37c5a70e963c945fe3`

**Comment by IncoCode** [comment] 2015-10-29 19:45
@rkcreation fixed in my pr, thanks for reporting this problem.

**Closed** 2015-10-30 09:06 UTC
Labels: bug
